# Generated by Django 5.0.6 on 2024-05-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diams_cms_application', '0002_alter_portalpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalpage',
            name='category',
            field=models.CharField(choices=[('hobby', '趣味'), ('technology', '技術系')], default='hobby', max_length=255),
        ),
    ]
